#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI2 --primary --mode 1920x1080 --rotate normal --output eDP1 --mode 1366x768 --rotate normal --right-of HDMI2

bspc monitor HDMI2 -d 1 2 3 4 5
bspc monitor eDP1 -d 6 7 8 9 10

bspc config border_width        0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#073642"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
# ~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
feh --bg-fill ~/Pictures/forest.jpg &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &
